language: bash
dist: trusty

virtualenv:
    system_site_packages: true

before_install:

  - pip install -I requests>=2.2.0
  - sudo apt-get -qq update
  - sudo apt-get install -y linkchecker
  
  
install:

  - git clone https://github.com/evilnick/documentation-builder
  - pip3 install ./documentation-builder
 

script:
  - python3 ./documentation-builder/bin/documentation-builder
  - bash .ci/links.sh
